function features= feat()

features = {
    'use of light';
    'avg saturation';
    'std saturation';
    'std brightness';
    'valence';
    'dominance';
    'arousal';
    'hue circular variance';
    'colorfulness';
    'black';
    'blue';
    'brown';
    'gray';
    'green';
    'orange';
    'pink';
    'purple';
    'red';
    'white';
    'yellow';
    'pers. perc. of edges pixels';
    'level of detail';
    'avg region size';
    'low DOF - hue';
    'low DOF - saturation';
    'low DOF - brightness';
    'rule of thirds - saturation';
    'rule of thirds - brightness';
    'image size';
    'gray distribution entropy';
    'hue wavelet - lev 1';
    'hue wavelet - lev 2';
    'hue wavelet - lev 3';
    'saturation wavelet - lev 1';
    'saturation wavelet - lev 2';
    'saturation wavelet - lev 3';
    'brightness wavelet - lev 1';
    'brightness wavelet - lev 2';
    'brightness wavelet - lev 3';
    'hue wavelet avg';
    'saturation wavelet avg';
    'brightness wavelet avg';
    'Tamura coarseness';
    'Tamura contrast';
    'Tamura directionality';
    'GLCM contrast - hue';
    'GLCM correlation - hue';
    'GLCM energy - hue';
    'GLCM homogeneity - hue';
    'GLCM contrast - saturation';
    'GLCM correlation - saturation';
    'GLCM energy - saturation';
    'GLCM homogeneity - saturation';
    'GLCM contrast - brightness';
    'GLCM correlation -  brightness';
    'GLCM energy - brightness';
    'GLCM homogeneity - brightness';
    'GIST - channel 1';
    'GIST - channel 2';
    'GIST - channel 3';
    'GIST - channel 4';
    'GIST - channel 5';
    'GIST - channel 6';
    'GIST - channel 7';
    'GIST - channel 8';
    'GIST - channel 9';
    'GIST - channel 10';
    'GIST - channel 11';
    'GIST - channel 12';
    'GIST - channel 13';
    'GIST - channel 14';
    'GIST - channel 15';
    'GIST - channel 16';
    'GIST - channel 17';
    'GIST - channel 18';
    'GIST - channel 19';
    'GIST - channel 20';
    'GIST - channel 21';
    'GIST - channel 22';
    'GIST - channel 23';
    'GIST - channel 24';
    'number of faces'; 
    
        };
    